# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'textureDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for textureDemo
	pod 'Texture',:git=>'https://github.com/TextureGroup/Texture.git'
	pod 'TaboolaSDK'
    pod 'SVProgressHUD',:git=>'https://github.com/SVProgressHUD/SVProgressHUD.git'
end
